### ISSUE TITLE
[HELP] запуск на сервере (localhost) и использование как прокси ip:port в браузере

### ISSUE THREAD

**Issue by madzohan** [vimusov/torxy#1]
Доброго времени суток, в сетях не силен, но смог настроить DOH over TOR с помощью dnscrypt-proxy и вот хочу поднять прокси для https запросов через TOR (privoxy не умеет и ищу решение проблемы) и немного покопавшись в сети нашел Вашу реализацию, но не понимаю как ее правильно завести в данном случае

```
sudo python3 -m torxy -dD
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:__main__:Start serving requests on '169.254.254.254:3128'.

# далее в браузере включаю проксю 169.254.254.254:3128

DEBUG:__main__:Error "Client IP '169.254.254.254' matches with destination address:" occurred getting client address.
```

**Comment by madzohan** [comment]
# if client_ip == ip:
        #     raise InvalidClientAddress(f'Client IP {client_ip!r} matches with destination address:')
закоментил и кое-как начало бежать, но печально работает ...

**Comment by vimusov** [comment]
@madzohan 

Здравствуйте.

> не понимаю как ее правильно завести в данном случае

Никак. torxy изначально создан для работы исключительно в прозрачном режиме и никак иначе.
